-- AlterTable
ALTER TABLE "public"."Team" ADD COLUMN     "totalEarningsAll" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalEarningsCard" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalEarningsCash" DOUBLE PRECISION NOT NULL DEFAULT 0;
